apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: bookinfo-helmchart
  namespace: open-cluster-management
  labels:
    app: bookinfo
spec:
  channel: open-cluster-management/chart
  name: bookinfo
  packageFilter:
    version: 1.0.7
  placement:
    placementRef:
      kind: PlacementRule
      name: dev-placementrule
  overrides:
  - clusterName: "/"
    clusterOverrides:
    - path: "metadata.namespace"
      value: bookinfo
  packageOverrides:
  - packageName: bookinfo
    packageOverrides:
    - path: spec.releaseName
      value: bookinfo-demo
    - path: spec.values
      value: |
        ingress:
          host: bookinfo.apps.spoke-23.demo.red-chesterfield.com